baseURL = "/"
languageCode = "en-us"
title = "Moritz Gunz"
languagecode = "en"
defaultcontentlanguage = "en"
theme = "coder"

[params]
author = "Moritz Gunz"
info = "Full Stack Web Engineer available for hire"
description = "Moritz Gunz - Full Stack Web Engineer"
avatarurl = "images/profile.jpg"
keywords = "web, developer, engineer, full, stack"
footercontent = "🌈"
hideCredits = true
hideCopyright = true

[[params.social]]
name = "Github"
weight = 1
url = "https://github.com/NeoLegends"

[[params.social]]
name = "E-Mail"
weight = 3
url = "mailto:yo@moritzgunz.de"
